name: Non-Production Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  temp:
    name: Temp Job
    runs-on: ubuntu-latest
    steps:
      - name: Temp Step
        run: echo "Hello World"
