name: Production Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependecies
        run: npm ci

      - name: Build Gatsby
        run: npm run build

      - name: Bundle build into an Artifact
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt-get install zip -y
          zip -r ${{ github.sha }}.zip public

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ${{ github.sha }}.zip

  deploy:
    name: Deploy Code
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Prepare the build artifact
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt-get install zip unzip -y
          unzip ${{ github.sha }}.zip -d public

      - name: Upload to S3
        run: aws s3 cp public s3://${{ secrets.S3_BUCKET_PROD }}/ --recursive --acl public-read
