name: Python Lambda Pipeline

on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Build Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.0

      - name: Install dependencies
        run: |
          cd src/
          pip install -r requirements.txt -t .
      
      - name: Bundle code into a Build Artifact
        run: |
          cd src/
          zip -r ../${{ github.sha }}.zip .

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ${{ github.sha }}.zip
