name: Container Memory Action Pipeline

on: [push]

jobs:
  container_job:
    name: A job to output container info
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Container Step
        id: unus-container
        uses: ./
        with:
          container-name: Unus Annus

      - name: Container Step
        id: memento-container
        uses: ./

      - name: Get the Unus Annus output memory
        run: echo "The memory is ${{ steps.unus-container.outputs.memory }}"

      - name: Get the Memento output memory
        run: echo "The memory is ${{ steps.memento-container.outputs.memory }}"
